const {chromium} = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
import assert from 'node:assert/strict';
import {checkEdits} from './browser-edits.mjs';
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH,headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:8765');
await page.getByRole('heading',{name:'The leaderboard'}).waitFor();
await page.screenshot({path:'/tmp/round-table-desktop.png',fullPage:true});
await page.getByRole('button',{name:'My picks',exact:true}).click();
await page.locator('#kind').selectOption('preseason');
for(const name of ['Amol Rajan','Bella Ramsey','James Acaster'])await page.getByRole('button',{name:new RegExp(name)}).click();
await page.getByRole('button',{name:'Save picks',exact:true}).click();
await page.reload();await page.getByRole('button',{name:'My picks',exact:true}).click();await page.locator('#kind').selectOption('preseason');
assert.equal(await page.locator('[aria-pressed=true]').count(),3);
await page.getByRole('button',{name:'Organiser',exact:true}).click();
await page.locator('#new-name').fill('New player');await page.locator('#new-email').fill('new@example.com');await page.getByRole('button',{name:'Add player',exact:true}).click();
await page.getByRole('row',{name:'New player new@example.com Player Make New player an organiser',exact:true}).waitFor();
await page.locator('summary').filter({hasText:'Record starting roles'}).click();
for(const el of await page.locator('[data-start]').all())await el.selectOption('Faithful');
await page.locator('[data-start="4"]').selectOption('Traitor');await page.locator('[data-start="5"]').selectOption('Traitor');
await page.getByRole('button',{name:'Save season controls',exact:true}).click();
await page.locator('#admin-episode').selectOption('1');
await page.locator('summary').filter({hasText:'Active cast and roles'}).click();await page.getByRole('button',{name:'Copy starting roles'}).click();await page.getByRole('button',{name:'Save episode setup',exact:true}).click();
await page.locator('#admin-episode').selectOption('2');await page.locator('summary').filter({hasText:'Active cast and roles'}).click();await page.getByRole('button',{name:'Copy previous episode roster'}).click();await page.getByRole('button',{name:'Save episode setup',exact:true}).click();
await page.getByRole('button',{name:'My picks',exact:true}).click();await page.locator('#kind').selectOption('weekly');
for(const id of ['4','5','6','7','8','9','10','11'])await page.locator(`[data-pick="${id}"]`).click();await page.locator('#captain').selectOption('4');await page.getByRole('button',{name:'Save picks',exact:true}).click();
await page.getByRole('button',{name:'Update picks',exact:true}).waitFor();
await checkEdits(page);
await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Standings',exact:true}).click();
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
await page.screenshot({path:'/tmp/round-table-mobile.png',fullPage:true});
assert.deepEqual(errors,[]);console.log('Browser passed: preseason persistence, add player, roster setup, weekly draft, unsaved-edit protection, section save boundaries, scoring selection, failed-save recovery, episode context, mobile layout, no JS errors.');
await browser.close();
