const {PGlite} = await import(process.env.PGLITE_MODULE || '@electric-sql/pglite');
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role anon; create role authenticated; create schema auth;
create function auth.jwt() returns jsonb language sql as $$ select current_setting('test.jwt',true)::jsonb $$;
create function auth.uid() returns uuid language sql as $$ select (auth.jwt()->>'sub')::uuid $$;`);
await db.exec(readFileSync(new URL('../schema.sql',import.meta.url),'utf8'));
const s=JSON.parse(readFileSync(new URL('../web/seed.json',import.meta.url)));
s.characters.forEach((c,i)=>s.episodes[1].roster[c.id]={role:i<2?'Traitor':'Faithful',status:'Active'});
await db.query('insert into public.league_config values(1,$1,0)',[s]);
await db.exec(`insert into public.league_players(email,name,is_admin) values('admin@example.com','Admin',true),('player@example.com','Player',false);`);
async function as(email){await db.query("select set_config('test.jwt',$1,false)",[JSON.stringify({email,sub:'11111111-1111-4111-8111-111111111111'})]);await db.exec('set role authenticated');}
await as('player@example.com');
const draft={picks:['4','5','6','7','8','9','10','11'],captain:'4'};
await db.query("select public.save_entry('weekly',2,$1)",[draft]);
await assert.rejects(()=>db.query("select public.save_entry('weekly',2,$1)",[{...draft,captain:'12'}]),/Captain/);
await assert.rejects(()=>db.query('select public.save_league($1,0)',[s]),/Organiser/);
await assert.rejects(()=>db.query('select * from public.league_entries'),/permission denied/);
await db.exec('reset role');await as('admin@example.com');
let read=(await db.query('select public.read_league() as data')).rows[0].data;
assert.equal(read.entries.length,0,'Other players’ open drafts stay hidden even from organiser');
const invalid=structuredClone(s);invalid.episodes[1].roster['4'].status='Banished';
await assert.rejects(()=>db.query('select public.save_league($1,0)',[invalid]),/invalidate/);
s.episodes[1].locked=true;await db.query('select public.save_league($1,0)',[s]);
read=(await db.query('select public.read_league() as data')).rows[0].data;assert.equal(read.entries.length,1);
await assert.rejects(()=>db.query('select public.save_league($1,0)',[s]),/another window/);
await db.query("select public.add_player('new@example.com','New player')");
await db.exec('reset role');await as('player@example.com');
await assert.rejects(()=>db.query("select public.save_entry('weekly',2,$1)",[draft]),/locked/);
await assert.rejects(()=>db.query('select public.export_league()'),/Organiser/);
await db.exec('reset role');await as('outsider@example.com');
await assert.rejects(()=>db.query('select public.read_league()'),/not on this league/);
await assert.rejects(()=>db.query("select public.save_entry('preseason',1,$1)",[{picks:['4','5','6']}]),/Not a league member/);
console.log('Database passed: schema, membership, permissions, draft validation, privacy, locks, revision conflicts and add player.');
await db.close();
